name: Update Crypto Prices

on:
  schedule:
    - cron: '4,9,14,19,24,29,34,39,44,49,54,59 * * * *'
  workflow_dispatch:

jobs:
  update_prices:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the correct branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main # The action below will push to this branch

      # ... your setup-python and install steps ...
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run price update script
        run: python update_prices.py

      # Step 5: Get Current Date
      - name: Get Current Date
        id: get_date
        run: echo "DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      # Step 6: Add, Commit and Push Changes (Corrected)
      - name: Add, Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          # The message for the commit
          message: "Update crypto prices at ${{ env.DATE }}"
          
          # Add the --allow-empty flag to the git commit command
          commit: --allow-empty
          
          # The action will commit and push to the branch checked out in Step 1
