name: Update Crypto Prices

on:
  schedule:
    - cron: '4,9,14,19,24,29,34,39,44,49,54,59 * * * *' # Runs every five minutes
  workflow_dispatch:      # Allows manual trigger

jobs:
  update_prices:
    runs-on: ubuntu-latest
    
    # Add permissions for the job
    permissions:
      contents: write # Allows the action to push to the repository

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4 # Use the latest version
        with:
          ref: main         # Ensure the main branch is checked out
          fetch-depth: 0    # Fetch all history for all branches and tags

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5 # Use the latest version
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run the price update script
      - name: Run price update script
        run: python update_prices.py

      # Step 5: Get Current Date
      - name: Get Current Date
        id: get_date
        run: echo "DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      # Step 6: Add, Commit, and Push Changes
      - name: Add, Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "naynaingoo2003"
          author_email: "naynaingoo.official@gmail.com"
          message: "Update crypto prices at ${{ env.DATE }}"
          branch: main
          add: 'README.md' # Be explicit about what file to check
          add_options: '--allow-empty' # Create a commit even if there are no changes
