name: Update Crypto Prices

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every five minutes
  workflow_dispatch:      # Allows manual trigger

jobs:
  update_prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run price update script
        run: python update_prices.py

      - name: Get Current Date
        id: get_date
        run: echo "DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git config --local user.email "naynaingoo.official@gmail.com"
          git config --local user.name "naynaingoo2003"
          git add README.md
          git commit -m "Update crypto prices on ${{ env.DATE }}" || echo "No changes to commit"

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update crypto prices on ${{ env.DATE }}"
